-- Create the posts table
create table posts (
  id bigint generated by default as identity primary key,
  author text not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable realtime for the posts table
alter table posts replica identity full;

-- Add image_url column to posts table
alter table posts add column image_url text; 